version: '3.8'

services:
  ml-bot:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

  chromadb:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    volumes:
      - ./data/chroma:/chroma